[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "claude-task-master-wrapper"
version = "2.0.0"
description = "Task management wrapper for Python integration"
dependencies = []

[tool.setuptools]
py-modules = ["task_master_wrapper"]

[project.scripts]
task-master-py = "task_master_wrapper:main"