name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '{{cookiecutter.python_version}}'
        cache: 'pip'
    - run: pip install pre-commit pytest ruff black bandit -q
    - run: pre-commit run --all-files
    - run: pytest -q{% if cookiecutter.use_database != "no" %} --maxfail=1{% endif %}
      env:
        {% if cookiecutter.use_database == "postgresql" %}
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        {% elif cookiecutter.use_database == "sqlite" %}
        DATABASE_URL: sqlite:///test.db
        {% endif %}
        CI: true